### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Alwaki** [Alwaki/DiracSVT#2]
- [x] Match license in Repo and in overleaf document
- [x] Change python file to handle multiple states
- [x] Test all three builds final on new pc setup
- [x] Add boundary condition in paper
- [x] Add other gap equation
- [x] Try to optimize conditions for matlab and python to get slightly better results in bad runs
- [x] Ensure all declarations at top of code are good to go (authors, date, description, etc)
